version: '3.7'

services:
  db:
    image: mongo:4.2
    container_name: mongo-projet-impressario
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: maquettes
    # https://stackoverflow.com/questions/66317184/github-actions-cannot-connect-to-mongodb-service
    options: >-
      --health-cmd mongo
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
  # app:
  #   build: .
  #   container_name: app-projet-impressario
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app